### ISSUE TITLE
Amazing - using it right now!

### ISSUE THREAD

**Issue by fire17** [anikraj1994/Remote#1]
first of all thanks a lot! the setup was super simple with the qr! and everything works great!!!
would love to get a version with the downloads page...😊

also, Id like to make a simple python script that does this, so it's basically just json over http? any thing I should know more? love to chat about this if you like

**Comment by anikraj1994** [comment]
Hey!

Once you have the ip and port of the host machine, you can use JSON RPC calls. Refer the following files for more details:

1. [PopcornService.java](https://github.com/anikraj1994/Remote/blob/master/app/src/main/java/com/anikrajc/remote/api/PopcornService.java)
This class handles the core RPC calls
2. [JSONRPC.java](https://github.com/anikraj1994/Remote/blob/master/app/src/main/java/com/anikrajc/remote/util/network/JSONRPC.java)
This class constructs the RPC JSON object used in the network request.

Wishing you best on your project.

Closing this issue as it is not really an issue.
